//! `concir-instrument` v2: rewrite a free std-only Rust program onto
//! instrumented `cir_trace::sync` wrapper types.
//!
//! Unlike the v1 call-site annotator (which inserts `cir_trace::ev` before each
//! operation and therefore cannot see guard-drop unlocks), v2 replaces the
//! `std::sync::{Mutex, Condvar}` names with wrappers whose `lock`/`Guard::drop`,
//! `wait`, `notify_*` emit operation-bound `(tag, op, resource, sid)` events.
//! Resource names are derived from the binding the constructor is assigned to,
//! so `Arc::clone`d handles share one name. Sids are generated by
//! `(resource, op, occurrence)` at runtime.
//!
//! The transform is intentionally conservative: it handles `Mutex` and
//! `Condvar` (the primitives of the lock-order/condvar families) and reports
//! everything it cannot cover (RwLock, barriers, atomics, macro bodies,
//! generics) as a limitation instead of silently dropping it.
//! Thread creation is collected across expressions, parseable macro arguments,
//! loops and functions. Ordinary and imported `spawn` calls and lexically bound
//! scoped spawns are traced; Builder and unknown spawn methods remain unsupported.
//! Names prefer a unique worker call, then a direct handle binding, then the
//! first worker call, and finally file order. Loop sites retain one resource.

use std::collections::BTreeMap;

use syn::spanned::Spanned;
use syn::visit::Visit;
use syn::{Expr, ExprCall, ExprMethodCall, File, Pat, Stmt};

/// Runtime emitted next to the instrumented source as `cir_trace.rs`.
pub const RUNTIME: &str = r#"// Generated cir_trace runtime v2 (std only, wrapper types).
#![allow(dead_code)]
use std::collections::HashMap;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::OnceLock;

static EVENTS: OnceLock<std::sync::Mutex<Vec<(String, String, String, String)>>> = OnceLock::new();
static MAIN: OnceLock<std::thread::ThreadId> = OnceLock::new();
static NEXT_TAG: AtomicU64 = AtomicU64::new(1);
static SIDS: OnceLock<std::sync::Mutex<HashMap<String, u64>>> = OnceLock::new();

thread_local! {
    static TAG: std::cell::RefCell<Option<String>> = const { std::cell::RefCell::new(None) };
}

/// Pin the main thread's tag to `t0` before any worker can run.
pub fn init() {
    let _ = MAIN.set(std::thread::current().id());
    let _ = EVENTS.get_or_init(|| std::sync::Mutex::new(Vec::new()));
    let _ = concir_sync::set_recorder(record);
}

/// Thread tag: the eager spawn-order tag when set, `t0` for main, and a lazy
/// fallback for threads created without the helper.
pub fn tag() -> String {
    if let Some(t) = TAG.with(|t| t.borrow().clone()) {
        return t;
    }
    let tid = std::thread::current().id();
    let main = *MAIN.get_or_init(|| tid);
    if tid == main {
        return "t0".to_string();
    }
    let n = NEXT_TAG.fetch_add(1, Ordering::SeqCst);
    let name = format!("t{}", n);
    TAG.with(|t| *t.borrow_mut() = Some(name.clone()));
    name
}

fn next_sid(resource: &str, op: &str) -> String {
    let key = format!("{resource}:{op}");
    let sids = SIDS.get_or_init(|| std::sync::Mutex::new(HashMap::new()));
    let mut map = sids.lock().unwrap();
    let c = map.entry(key.clone()).or_insert(0);
    *c += 1;
    format!("{key}#{c}")
}

pub fn record(op: &str, resource: &str) {
    let sid = next_sid(resource, op);
    let events = EVENTS.get_or_init(|| std::sync::Mutex::new(Vec::new()));
    events
        .lock()
        .unwrap()
        .push((tag(), op.to_string(), resource.to_string(), sid));
}

/// Spawn a worker and record it; the child's completion is witnessed by the
/// program finishing (a finished trace implies `main` returned).
pub fn spawn<F, T>(name: &'static str, f: F) -> std::thread::JoinHandle<T>
where
    F: FnOnce() -> T + Send + 'static,
    T: Send + 'static,
{
    record("spawn", name);
    let n = NEXT_TAG.fetch_add(1, Ordering::SeqCst);
    let tag = format!("t{}", n);
    std::thread::spawn(move || {
        TAG.with(|t| *t.borrow_mut() = Some(tag));
        f()
    })
}

/// Preserve std's scoped borrowing, implicit joins and closure return value.
pub fn scope<'env, F, T>(f: F) -> T
where
    F: for<'scope> FnOnce(&'scope std::thread::Scope<'scope, 'env>) -> T,
{
    std::thread::scope(f)
}

pub fn scope_spawn<'scope, 'env, F, T>(
    s: &'scope std::thread::Scope<'scope, 'env>, name: &'static str, f: F,
) -> std::thread::ScopedJoinHandle<'scope, T>
where
    F: FnOnce() -> T + Send + 'scope,
    T: Send + 'scope,
{
    record("spawn", name);
    let n = NEXT_TAG.fetch_add(1, Ordering::SeqCst);
    let tag = format!("t{}", n);
    s.spawn(move || {
        TAG.with(|t| *t.borrow_mut() = Some(tag));
        f()
    })
}

pub fn finish() {
    if let Ok(path) = std::env::var("CIR_TRACE_OUT") {
        let events = EVENTS.get_or_init(|| std::sync::Mutex::new(Vec::new()));
        let guard = events.lock().unwrap();
        let mut out = String::new();
        for (t, op, r, s) in guard.iter() {
            out.push_str(&format!(
                "{{\"t\":\"{}\",\"sid\":\"{}\",\"op\":\"{}\",\"r\":\"{}\"}}\n",
                t, s, op, r
            ));
        }
        let _ = std::fs::write(path, out);
    }
}

pub mod sync {
    use super::record;
    use std::ops::{Deref, DerefMut};
    use std::sync::{Condvar as StdCondvar, LockResult, Mutex as StdMutex};

    pub struct Mutex<T> {
        inner: StdMutex<T>,
        name: &'static str,
    }

    pub struct Guard<'a, T> {
        inner: Option<std::sync::MutexGuard<'a, T>>,
        name: &'static str,
        armed: bool,
    }

    impl<T> Mutex<T> {
        pub fn new(value: T) -> Self {
            Self::new_named("mutex", value)
        }
        pub const fn new_named(name: &'static str, value: T) -> Self {
            Mutex { inner: StdMutex::new(value), name }
        }
        pub fn lock(&self) -> LockResult<Guard<'_, T>> {
            match self.inner.lock() {
                Ok(g) => {
                    record("mutex_lock", self.name);
                    Ok(Guard { inner: Some(g), name: self.name, armed: true })
                }
                Err(e) => {
                    let g: std::sync::MutexGuard<'_, T> = e.into_inner();
                    record("mutex_lock", self.name);
                    Ok(Guard { inner: Some(g), name: self.name, armed: true })
                }
            }
        }
    }

    impl<T: std::fmt::Debug> std::fmt::Debug for Mutex<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            std::fmt::Debug::fmt(&self.inner, f)
        }
    }

    impl<T: Default> Default for Mutex<T> {
        fn default() -> Self { Self::new(T::default()) }
    }

    impl<T> Mutex<T> {
        pub fn try_lock(&self) -> std::sync::TryLockResult<Guard<'_, T>> {
            match self.inner.try_lock() {
                Ok(g) => {
                    record("mutex_lock", self.name);
                    Ok(Guard { inner: Some(g), name: self.name, armed: true })
                }
                Err(std::sync::TryLockError::WouldBlock) => Err(std::sync::TryLockError::WouldBlock),
                Err(std::sync::TryLockError::Poisoned(e)) => {
                    // A failed try_lock emits no event, including on guard drop.
                    let guard = Guard { inner: Some(e.into_inner()), name: self.name, armed: false };
                    Err(std::sync::TryLockError::Poisoned(std::sync::PoisonError::new(guard)))
                }
            }
        }
        pub fn into_inner(self) -> LockResult<T> { self.inner.into_inner() }
        pub fn get_mut(&mut self) -> LockResult<&mut T> { self.inner.get_mut() }
        pub fn is_poisoned(&self) -> bool { self.inner.is_poisoned() }
    }

    impl<'a, T> Deref for Guard<'a, T> {
        type Target = T;
        fn deref(&self) -> &T {
            self.inner.as_ref().unwrap()
        }
    }

    impl<'a, T> DerefMut for Guard<'a, T> {
        fn deref_mut(&mut self) -> &mut T {
            self.inner.as_mut().unwrap()
        }
    }

    impl<'a, T> Drop for Guard<'a, T> {
        fn drop(&mut self) {
            if self.armed {
                record("mutex_unlock", self.name);
            }
        }
    }

    pub struct Condvar {
        inner: StdCondvar,
        name: &'static str,
    }

    impl std::fmt::Debug for Condvar {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            std::fmt::Debug::fmt(&self.inner, f)
        }
    }

    impl Condvar {
        pub fn wait_timeout<'a, T>(&self, mut guard: Guard<'a, T>, dur: std::time::Duration)
            -> LockResult<(Guard<'a, T>, std::sync::WaitTimeoutResult)>
        {
            let name = guard.name;
            guard.armed = false;
            let inner = guard.inner.take().expect("condvar guard consumed twice");
            let result = self.inner.wait_timeout(inner, dur);
            record("condvar_wait", self.name);
            match result {
                Ok((g, timed)) => Ok((Guard { inner: Some(g), name, armed: true }, timed)),
                Err(e) => {
                    let (g, timed) = e.into_inner();
                    Err(std::sync::PoisonError::new((Guard { inner: Some(g), name, armed: true }, timed)))
                }
            }
        }
        pub fn wait_timeout_while<'a, T, F>(
            &self, mut guard: Guard<'a, T>, dur: std::time::Duration, f: F,
        ) -> LockResult<(Guard<'a, T>, std::sync::WaitTimeoutResult)>
        where F: FnMut(&mut T) -> bool,
        {
            let name = guard.name;
            guard.armed = false;
            let inner = guard.inner.take().expect("condvar guard consumed twice");
            let result = self.inner.wait_timeout_while(inner, dur, f);
            record("condvar_wait", self.name);
            match result {
                Ok((g, timed)) => Ok((Guard { inner: Some(g), name, armed: true }, timed)),
                Err(e) => {
                    let (g, timed) = e.into_inner();
                    Err(std::sync::PoisonError::new((Guard { inner: Some(g), name, armed: true }, timed)))
                }
            }
        }
    }

    impl Default for Condvar {
        fn default() -> Self {
            Self::new()
        }
    }

    impl Condvar {
        pub fn new() -> Self {
            Self::new_named("condvar")
        }
        pub const fn new_named(name: &'static str) -> Self {
            Condvar { inner: StdCondvar::new(), name }
        }
        pub fn wait<'a, T>(&self, mut guard: Guard<'a, T>) -> LockResult<Guard<'a, T>> {
            let name = guard.name;
            guard.armed = false;
            let inner: std::sync::MutexGuard<'a, T> =
                guard.inner.take().expect("condvar guard consumed twice");
            // One model step: the release/reacquire around the wait is implicit,
            // so no mutex_unlock/mutex_lock events are emitted here.
            let result = self.inner.wait(inner);
            record("condvar_wait", self.name);
            match result {
                Ok(g) => Ok(Guard { inner: Some(g), name, armed: true }),
                Err(_) => Ok(Guard { inner: None, name, armed: false }),
            }
        }
        pub fn wait_while<'a, T, F>(&self, mut guard: Guard<'a, T>, mut f: F)
            -> LockResult<Guard<'a, T>>
        where
            F: FnMut(&mut T) -> bool,
        {
            let name = guard.name;
            guard.armed = false;
            let inner: std::sync::MutexGuard<'a, T> =
                guard.inner.take().expect("condvar guard consumed twice");
            let result = self.inner.wait_while(inner, |v| f(v));
            record("condvar_wait", self.name);
            match result {
                Ok(g) => Ok(Guard { inner: Some(g), name, armed: true }),
                Err(_) => Ok(Guard { inner: None, name, armed: false }),
            }
        }
        pub fn notify_one(&self) {
            record("condvar_notify", self.name);
            self.inner.notify_one();
        }
        pub fn notify_all(&self) {
            record("condvar_notify_all", self.name);
            self.inner.notify_all();
        }
    }
}

"#;


#[derive(Debug, Clone, serde::Serialize, Default)]
pub struct Resource {
    pub name: String,
    pub kind: String,
    /// CIR-matching name (field / binding / channel token), separate from the
    /// runtime-unique `name` which carries the construction site.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    /// Construction-site byte offset: distinguishes two instances that share a
    /// name (e.g. two `S { m: Mutex::new(..) }` values).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub site: Option<String>,
    /// Spawn: the function the thread runs, when it is unambiguous.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub entry: Option<String>,
    /// Spawn: whether the closure body has exactly one non-builtin call.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub unique_entry: Option<bool>,
    /// One syntactic site can execute repeatedly (including iterator closures).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub in_loop: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name_source: Option<String>,
    /// Direct handle binding, even when the unique worker name takes precedence.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub binding: Option<String>,
}

#[derive(Debug, Clone)]
pub struct Wrapped {
    pub annotated: String,
    pub runtime: String,
    pub resources: Vec<Resource>,
    pub limitations: Vec<String>,
    pub harness_notes: Vec<String>,
}

struct Edit {
    start: usize,
    end: usize,
    text: String,
}

fn line_starts(src: &str) -> Vec<usize> {
    let mut starts = vec![0usize];
    for (i, b) in src.bytes().enumerate() {
        if b == b'\n' {
            starts.push(i + 1);
        }
    }
    starts
}

fn lc_offset(starts: &[usize], lc: proc_macro2::LineColumn) -> usize {
    let line = lc.line.saturating_sub(1).min(starts.len().saturating_sub(1));
    starts[line] + lc.column
}

fn leading_header_len(src: &str) -> usize {
    let mut offset = 0;
    for line in src.split_inclusive('\n') {
        let trimmed = line.trim_start();
        if trimmed.starts_with("//!") || trimmed.starts_with("#![") || trimmed.trim().is_empty() {
            offset += line.len();
        } else {
            break;
        }
    }
    offset
}

fn ctor_kind(path: &syn::Path) -> Option<&'static str> {
    let segs: Vec<String> = path.segments.iter().map(|s| s.ident.to_string()).collect();
    if segs.last().map(String::as_str) != Some("new") {
        return None;
    }
    match segs.get(segs.len().wrapping_sub(2)).map(String::as_str) {
        Some("Mutex") => Some("Mutex"),
        Some("Condvar") => Some("Condvar"),
        Some("Semaphore") => Some("Semaphore"),
        _ => None,
    }
}

struct CtorHit {
    new_start: usize,
    new_end: usize,
    open_brace: usize,
    empty_args: bool,
    kind: &'static str,
    /// Struct-literal field the constructor is assigned to, when any. Used as
    /// the resource name so field identity is recovered structurally.
    field: Option<String>,
}

struct SpawnHit {
    callee_start: usize,
    callee_end: usize,
    unique: bool,
    open_brace: usize,
    callee_name: Option<String>,
    binding: Option<String>,
    receiver: Option<String>,
    in_loop: bool,
}

/// The first plain function called inside a spawned closure, used to name the
/// thread after the worker it runs (falling back to order when absent).
struct FirstCall {
    name: Option<String>,
}

const BUILTIN_CALLS: &[&str] = &[
    "spawn", "scope", "drop", "Arc", "Box", "Some", "Ok", "Err", "None",
    "println", "print", "format", "Vec", "String", "vec", "panic",
    "clone", "new", "default", "from", "into", "with_capacity", "take",
    "replace", "swap", "unwrap", "expect",
];

impl<'ast> Visit<'ast> for FirstCall {
    fn visit_expr_call(&mut self, node: &'ast ExprCall) {
        if self.name.is_none() {
            if let Expr::Path(p) = &*node.func {
                if let Some(seg) = p.path.segments.last() {
                    let ident = seg.ident.to_string();
                    if !BUILTIN_CALLS.contains(&ident.as_str()) {
                        self.name = Some(ident);
                    }
                }
            }
        }
        syn::visit::visit_expr_call(self, node);
    }
}

/// The first call inside a closure body, descending through blocks.
fn closure_callee(expr: &Expr) -> Option<String> {
    match expr {
        Expr::Closure(c) => {
            let mut fc = FirstCall { name: None };
            fc.visit_expr(&c.body);
            fc.name
        }
        Expr::Block(b) => b.block.stmts.iter().rev().find_map(|s| match s {
            Stmt::Expr(e, _) => closure_callee(e),
            _ => None,
        }),
        _ => None,
    }
}

/// Count non-builtin calls in a closure body, to decide whether the thread
/// entry is unambiguous (`move || worker()` = 1) or not (`|| { helper(); w(); }`).
struct CallCounter {
    n: usize,
}

impl<'ast> Visit<'ast> for CallCounter {
    fn visit_expr_call(&mut self, node: &'ast ExprCall) {
        if let Expr::Path(p) = &*node.func {
            if let Some(seg) = p.path.segments.last() {
                if !BUILTIN_CALLS.contains(&seg.ident.to_string().as_str()) {
                    self.n += 1;
                }
            }
        }
        syn::visit::visit_expr_call(self, node);
    }
}

fn closure_call_count(expr: &Expr) -> usize {
    match expr {
        Expr::Closure(c) => {
            let mut counter = CallCounter { n: 0 };
            counter.visit_expr(&c.body);
            counter.n
        }
        Expr::Block(b) => b.block.stmts.iter().rev().find_map(|s| match s {
            Stmt::Expr(e, _) => Some(closure_call_count(e)),
            _ => None,
        }).unwrap_or(0),
        _ => 0,
    }
}

/// The function a `thread::spawn` runs. Handles both `spawn(move || f(..))` and
/// the block form `spawn({ let x = ..; move || f(x) })`, so the thread entry is
/// recovered structurally instead of from the handle name.
fn spawn_callee(args: &syn::punctuated::Punctuated<Expr, syn::Token![,]>) -> Option<String> {
    args.first().and_then(|expr| match plain_expr(expr) {
        Expr::Path(p) => p.path.segments.last().map(|s| s.ident.to_string()),
        other => closure_callee(other),
    })
}

fn spawn_unique(args: &syn::punctuated::Punctuated<Expr, syn::Token![,]>) -> bool {
    args.first().is_some_and(|expr| match plain_expr(expr) {
        Expr::Path(_) => true,
        other => closure_call_count(other) == 1,
    })
}

/// Only names resolved to std imports or an active scope parameter are special.
/// Cloning the small lexical environment at block/closure boundaries prevents
/// a local import or a shadowed scope parameter from leaking into siblings.
#[derive(Clone, Copy, PartialEq)]
enum ThreadName {
    Spawn,
    Scope,
    ScopeParam,
    Other,
}

struct SpawnCollector {
    starts: Vec<usize>,
    names: BTreeMap<String, ThreadName>,
    bindings: BTreeMap<usize, String>,
    hits: BTreeMap<usize, SpawnHit>,
    edits: Vec<Edit>,
    loop_depth: usize,
    limitations: Vec<String>,
}

fn use_leaves(tree: &syn::UseTree, prefix: &str, out: &mut Vec<(String, String)>) {
    match tree {
        syn::UseTree::Path(p) => use_leaves(&p.tree, &format!("{prefix}{}::", p.ident), out),
        syn::UseTree::Group(g) => {
            for t in &g.items { use_leaves(t, prefix, out); }
        }
        syn::UseTree::Name(n) => out.push((format!("{prefix}{}", n.ident), n.ident.to_string())),
        syn::UseTree::Rename(n) => out.push((format!("{prefix}{}", n.ident), n.rename.to_string())),
        syn::UseTree::Glob(_) => out.push((format!("{prefix}*"), "*".into())),
    }
}

fn plain_expr(expr: &Expr) -> &Expr {
    match expr {
        Expr::Paren(p) => plain_expr(&p.expr),
        Expr::Group(g) => plain_expr(&g.expr),
        _ => expr,
    }
}

impl SpawnCollector {
    fn new(starts: Vec<usize>) -> Self {
        Self { starts, names: BTreeMap::new(), bindings: BTreeMap::new(),
               hits: BTreeMap::new(), edits: Vec::new(), loop_depth: 0,
               limitations: Vec::new() }
    }

    fn offset(&self, span: proc_macro2::Span) -> usize {
        lc_offset(&self.starts, span.start())
    }

    fn import(&mut self, item: &syn::ItemUse, glob_only: bool) {
        let mut leaves = Vec::new();
        use_leaves(&item.tree, "", &mut leaves);
        for (path, local) in leaves {
            if glob_only {
                if path == "std::thread::*" {
                    self.names.insert("spawn".into(), ThreadName::Spawn);
                    self.names.insert("scope".into(), ThreadName::Scope);
                }
                continue;
            }
            if local == "*" { continue; }
            let kind = match path.as_str() {
                "std::thread::spawn" => ThreadName::Spawn,
                "std::thread::scope" => ThreadName::Scope,
                _ => ThreadName::Other,
            };
            self.names.insert(local, kind);
        }
    }

    fn items<'a>(&mut self, items: impl Iterator<Item = &'a syn::Item> + Clone) {
        // Explicit items/imports beat globs regardless of declaration order.
        // All items are visible throughout their lexical block.
        for item in items.clone() {
            if let syn::Item::Use(u) = item { self.import(u, true); }
        }
        for item in items {
            match item {
                syn::Item::Use(u) => self.import(u, false),
                syn::Item::Fn(f) => { self.names.insert(f.sig.ident.to_string(), ThreadName::Other); }
                _ => {}
            }
        }
    }

    fn bind_pat(&mut self, pat: &Pat, kind: ThreadName) {
        struct Idents(Vec<String>);
        impl<'ast> Visit<'ast> for Idents {
            fn visit_pat_ident(&mut self, p: &'ast syn::PatIdent) {
                self.0.push(p.ident.to_string());
                syn::visit::visit_pat_ident(self, p);
            }
        }
        let mut ids = Idents(Vec::new());
        ids.visit_pat(pat);
        for id in ids.0 { self.names.insert(id, kind); }
    }

    fn thread_call(&self, expr: &Expr, kind: ThreadName) -> bool {
        let Expr::Path(p) = plain_expr(expr) else { return false };
        let segs: Vec<_> = p.path.segments.iter().map(|s| s.ident.to_string()).collect();
        let member = if kind == ThreadName::Spawn { "spawn" } else { "scope" };
        match segs.as_slice() {
            [name] => self.names.get(name) == Some(&kind),
            [module, name] => module == "thread" && name == member,
            [root, module, name] => root == "std" && module == "thread" && name == member,
            _ => false,
        }
    }

    fn scope_receiver(&self, expr: &Expr) -> Option<String> {
        let Expr::Path(p) = plain_expr(expr) else { return None };
        let id = p.path.get_ident()?.to_string();
        (self.names.get(&id) == Some(&ThreadName::ScopeParam)).then_some(id)
    }

    fn hit(&mut self, start: usize, end: usize, open: usize,
           args: &syn::punctuated::Punctuated<Expr, syn::Token![,]>, receiver: Option<String>) {
        self.hits.entry(start).or_insert_with(|| SpawnHit {
            callee_start: start, callee_end: end, open_brace: open,
            unique: spawn_unique(args), callee_name: spawn_callee(args),
            binding: self.bindings.get(&start).cloned(), receiver,
            in_loop: self.loop_depth > 0,
        });
    }

    fn closure(&mut self, c: &syn::ExprClosure, scope_param: bool) {
        let saved = self.names.clone();
        for pat in &c.inputs {
            self.bind_pat(pat, if scope_param { ThreadName::ScopeParam } else { ThreadName::Other });
        }
        self.visit_expr(&c.body);
        self.names = saved;
    }

    fn qualify_unparsed_calls(&mut self, tokens: proc_macro2::TokenStream, macro_name: &str) {
        use proc_macro2::{Delimiter, TokenTree};
        let tokens: Vec<_> = tokens.into_iter().collect();
        for (i, token) in tokens.iter().enumerate() {
            if let TokenTree::Group(group) = token {
                self.qualify_unparsed_calls(group.stream(), macro_name);
            }
            let TokenTree::Ident(ident) = token else { continue };
            let Some(TokenTree::Group(args)) = tokens.get(i + 1) else { continue };
            if args.delimiter() != Delimiter::Parenthesis { continue; }
            // Do not qualify methods, already-qualified paths or metavariables.
            if i > 0 && matches!(&tokens[i - 1], TokenTree::Punct(p)
                if matches!(p.as_char(), '.' | ':' | '$')) { continue; }
            let member = match self.names.get(&ident.to_string()) {
                Some(ThreadName::Spawn) => "spawn",
                Some(ThreadName::Scope) => "scope",
                _ => continue,
            };
            self.edits.push(Edit {
                start: self.offset(ident.span()),
                end: lc_offset(&self.starts, ident.span().end()),
                text: format!("std::thread::{member}"),
            });
            self.limitations.push(format!("unrewritten {member} in unparsed macro body: {macro_name}"));
        }
    }

    fn emit(&mut self, edits: &mut Vec<Edit>, resources: &mut Vec<Resource>) {
        edits.append(&mut self.edits);
        // BTreeMap both deduplicates sites and fixes fallback names to file order.
        for (index, hit) in self.hits.values().enumerate() {
            let (display, source) = if hit.unique && hit.callee_name.is_some() {
                (hit.callee_name.clone().unwrap(), "callee")
            } else if let Some(binding) = &hit.binding {
                (binding.clone(), "binding")
            } else if let Some(callee) = &hit.callee_name {
                (callee.clone(), "first_call")
            } else {
                (format!("spawn{index}"), "index")
            };
            let name = format!("{display}#{}", hit.callee_start);
            let (callee, prefix) = match &hit.receiver {
                Some(receiver) => ("crate::cir_trace::scope_spawn", format!("{receiver}, \"{name}\", ")),
                None => ("crate::cir_trace::spawn", format!("\"{name}\", ")),
            };
            edits.push(Edit { start: hit.callee_start, end: hit.callee_end, text: callee.into() });
            edits.push(Edit { start: hit.open_brace, end: hit.open_brace, text: prefix });
            resources.push(Resource {
                name, kind: "Spawn".into(), display: Some(display),
                site: Some(hit.callee_start.to_string()), entry: hit.callee_name.clone(),
                unique_entry: Some(hit.unique), binding: hit.binding.clone(),
                name_source: Some(source.into()), in_loop: hit.in_loop.then_some(true),
            });
        }
    }
}

impl<'ast> Visit<'ast> for SpawnCollector {
    fn visit_file(&mut self, file: &'ast File) {
        self.items(file.items.iter());
        syn::visit::visit_file(self, file);
    }

    fn visit_item_mod(&mut self, node: &'ast syn::ItemMod) {
        if let Some((_, items)) = &node.content {
            let saved = std::mem::take(&mut self.names);
            self.items(items.iter());
            for item in items { self.visit_item(item); }
            self.names = saved;
        }
    }

    fn visit_item_fn(&mut self, node: &'ast syn::ItemFn) {
        let saved = self.names.clone();
        let depth = std::mem::replace(&mut self.loop_depth, 0);
        self.names.retain(|_, kind| *kind != ThreadName::ScopeParam);
        for arg in &node.sig.inputs {
            if let syn::FnArg::Typed(t) = arg { self.bind_pat(&t.pat, ThreadName::Other); }
        }
        self.visit_block(&node.block);
        self.names = saved;
        self.loop_depth = depth;
    }

    fn visit_block(&mut self, block: &'ast syn::Block) {
        let saved = self.names.clone();
        self.items(block.stmts.iter().filter_map(|stmt| match stmt {
            Stmt::Item(item) => Some(item),
            _ => None,
        }));
        syn::visit::visit_block(self, block);
        self.names = saved;
    }

    fn visit_local(&mut self, local: &'ast syn::Local) {
        if let Some(init) = &local.init {
            let mut pat = &local.pat;
            while let Pat::Type(typed) = pat { pat = &typed.pat; }
            if let Pat::Ident(id) = pat {
                let expr = plain_expr(&init.expr);
                // A join/thread/id chain has the same start offset as its
                // receiver, but binds the chain's result, not a handle.
                let direct_spawn = match expr {
                    Expr::Call(call) => self.thread_call(&call.func, ThreadName::Spawn),
                    Expr::MethodCall(call) => call.method == "spawn"
                        && self.scope_receiver(&call.receiver).is_some(),
                    _ => false,
                };
                if direct_spawn {
                    self.bindings.insert(self.offset(expr.span()), id.ident.to_string());
                }
            }
            self.visit_expr(&init.expr);
            if let Some((_, expr)) = &init.diverge { self.visit_expr(expr); }
        }
        self.bind_pat(&local.pat, ThreadName::Other);
    }

    fn visit_item_use(&mut self, node: &'ast syn::ItemUse) {
        let mut leaves = Vec::new();
        use_leaves(&node.tree, "", &mut leaves);
        // Even an unused `use std::thread::scope;` matches Python's conservative
        // residual check. Import the equivalent forwarding helper instead.
        if leaves.iter().any(|(path, _)| path == "std::thread::scope") {
            let paths: Vec<_> = leaves.into_iter().map(|(path, name)| {
                let (path, name) = if let Some(parent) = path.strip_suffix("::self") {
                    (parent.to_string(), if name == "self" { parent.rsplit("::").next().unwrap().to_string() } else { name })
                } else { (path, name) };
                let path = if path == "std::thread::scope" { "crate::cir_trace::scope".into() } else { path };
                if path.rsplit("::").next() == Some(name.as_str()) { path }
                else { format!("{path} as {name}") }
            }).collect();
            self.edits.push(Edit {
                start: self.offset(node.tree.span()),
                end: lc_offset(&self.starts, node.tree.span().end()),
                text: format!("{{{}}}", paths.join(", ")),
            });
        }
    }

    fn visit_expr_call(&mut self, node: &'ast ExprCall) {
        if self.thread_call(&node.func, ThreadName::Spawn) {
            self.hit(self.offset(node.func.span()), lc_offset(&self.starts, node.func.span().end()),
                     self.offset(node.paren_token.span.open()) + 1, &node.args, None);
        } else if self.thread_call(&node.func, ThreadName::Scope) {
            if let Some(Expr::Closure(c)) = node.args.first().map(plain_expr) {
                if c.inputs.len() == 1 && matches!(c.inputs.first(), Some(Pat::Ident(_))) {
                    let before = self.limitations.len();
                    self.closure(c, true);
                    // Python's existing residual check does not recognize
                    // `.spawn_scoped`. Keep its enclosing std scope visible.
                    let unsupported = self.limitations[before..].iter()
                        .any(|note| note.contains("spawn_scoped"));
                    self.edits.push(Edit {
                        start: self.offset(node.func.span()),
                        end: lc_offset(&self.starts, node.func.span().end()),
                        text: if unsupported { "std::thread::scope" } else { "crate::cir_trace::scope" }.into(),
                    });
                    return;
                }
            }
            self.limitations.push("thread::scope requires an inline closure with a named parameter".into());
            self.edits.push(Edit {
                start: self.offset(node.func.span()),
                end: lc_offset(&self.starts, node.func.span().end()),
                text: "std::thread::scope".into(),
            });
        }
        syn::visit::visit_expr_call(self, node);
    }

    fn visit_expr_method_call(&mut self, node: &'ast ExprMethodCall) {
        if node.method == "spawn" {
            if let Some(receiver) = self.scope_receiver(&node.receiver) {
                self.hit(self.offset(node.receiver.span()), lc_offset(&self.starts, node.method.span().end()),
                         self.offset(node.paren_token.span.open()) + 1, &node.args, Some(receiver));
            } else {
                self.limitations.push("spawn method receiver is not a recognized scope parameter (Builder is unsupported)".into());
            }
        }
        if node.method == "spawn_scoped" {
            self.limitations.push("Builder spawn_scoped is not instrumented".into());
        }
        self.visit_expr(&node.receiver);
        let repeated = matches!(node.method.to_string().as_str(),
            "map" | "for_each" | "flat_map" | "filter_map" | "filter" | "fold" | "try_fold"
            | "try_for_each" | "scan" | "inspect" | "find" | "find_map" | "any" | "all"
            | "position" | "rposition" | "map_while" | "take_while" | "skip_while" | "reduce");
        for arg in &node.args {
            let depth = self.loop_depth;
            if repeated && matches!(plain_expr(arg), Expr::Closure(_)) { self.loop_depth += 1; }
            self.visit_expr(arg);
            self.loop_depth = depth;
        }
    }

    fn visit_expr_closure(&mut self, node: &'ast syn::ExprClosure) { self.closure(node, false); }

    fn visit_expr_for_loop(&mut self, node: &'ast syn::ExprForLoop) {
        self.visit_expr(&node.expr);
        let saved = self.names.clone();
        self.bind_pat(&node.pat, ThreadName::Other);
        self.loop_depth += 1;
        self.visit_block(&node.body);
        self.loop_depth -= 1;
        self.names = saved;
    }

    fn visit_expr_while(&mut self, node: &'ast syn::ExprWhile) {
        let saved = self.names.clone();
        self.loop_depth += 1;
        syn::visit::visit_expr_while(self, node);
        self.loop_depth -= 1;
        self.names = saved;
    }

    fn visit_expr_let(&mut self, node: &'ast syn::ExprLet) {
        self.visit_expr(&node.expr);
        self.bind_pat(&node.pat, ThreadName::Other);
    }

    fn visit_expr_if(&mut self, node: &'ast syn::ExprIf) {
        let saved = self.names.clone();
        self.visit_expr(&node.cond);
        self.visit_block(&node.then_branch);
        self.names = saved.clone();
        if let Some((_, branch)) = &node.else_branch { self.visit_expr(branch); }
        self.names = saved;
    }

    fn visit_expr_loop(&mut self, node: &'ast syn::ExprLoop) {
        self.loop_depth += 1;
        syn::visit::visit_expr_loop(self, node);
        self.loop_depth -= 1;
    }

    fn visit_arm(&mut self, node: &'ast syn::Arm) {
        let saved = self.names.clone();
        self.bind_pat(&node.pat, ThreadName::Other);
        syn::visit::visit_arm(self, node);
        self.names = saved;
    }

    fn visit_macro(&mut self, node: &'ast syn::Macro) {
        use syn::parse::Parser;
        // Parsing the original tokens retains source spans, including nested
        // macros. Never stringify/reparse: that would corrupt edit offsets.
        let list = syn::punctuated::Punctuated::<Expr, syn::Token![,]>::parse_terminated;
        if let Ok(args) = list.parse2(node.tokens.clone()) {
            for expr in &args { self.visit_expr(expr); }
        } else if let Ok(stmts) = syn::Block::parse_within.parse2(node.tokens.clone()) {
            let saved = self.names.clone();
            self.items(stmts.iter().filter_map(|stmt| match stmt {
                Stmt::Item(item) => Some(item),
                _ => None,
            }));
            for stmt in &stmts { self.visit_stmt(stmt); }
            self.names = saved;
        } else {
            let name = node.path.segments.last().unwrap().ident.to_string();
            self.limitations.push(format!("unparsed macro body: {name}"));
            self.qualify_unparsed_calls(node.tokens.clone(), &name);
        }
    }
}

struct CtorCollector {
    starts: Vec<usize>,
    hits: Vec<CtorHit>,
    skip_semaphore: bool,
    /// Nested `let` bindings are named by their own `Namer` visit. Collecting
    /// them again from an enclosing initializer would duplicate constructor edits.
    closure_depth: usize,
    current_field: Option<String>,
}

impl<'ast> Visit<'ast> for CtorCollector {
    fn visit_field_value(&mut self, node: &'ast syn::FieldValue) {
        let prev = self.current_field.take();
        if let syn::Member::Named(ident) = &node.member {
            self.current_field = Some(ident.to_string());
        }
        syn::visit::visit_field_value(self, node);
        self.current_field = prev;
    }

    fn visit_expr_closure(&mut self, node: &'ast syn::ExprClosure) {
        self.closure_depth += 1;
        syn::visit::visit_expr_closure(self, node);
        self.closure_depth -= 1;
    }

    fn visit_stmt(&mut self, node: &'ast Stmt) {
        if self.closure_depth > 0 {
            if let Stmt::Local(_) = node {
                return;
            }
        }
        syn::visit::visit_stmt(self, node);
    }

    fn visit_expr_call(&mut self, node: &'ast ExprCall) {
        if let Expr::Path(p) = &*node.func {
            if let Some(kind) = ctor_kind(&p.path) {
                if kind == "Semaphore" && self.skip_semaphore {
                    syn::visit::visit_expr_call(self, node);
                    return;
                }
                let ident = p.path.segments.last().expect("callee path").ident.clone();
                let open = lc_offset(&self.starts, node.paren_token.span.open().start()) + 1;
                self.hits.push(CtorHit {
                    new_start: lc_offset(&self.starts, ident.span().start()),
                    new_end: lc_offset(&self.starts, ident.span().end()),
                    open_brace: open,
                    empty_args: node.args.is_empty(),
                    kind,
                    field: self.current_field.clone(),
                });
            }
        }
        syn::visit::visit_expr_call(self, node);
    }
}


fn channel_op(method: &str) -> Option<&'static str> {
    match method {
        "recv" | "try_recv" => Some("channel_recv"),
        "send" | "try_send" => Some("channel_send"),
        _ => None,
    }
}

/// Base identifier and whether the receiver goes through a `Mutex` guard.
fn channel_target(expr: &Expr) -> (String, Option<String>) {
    match expr {
        Expr::MethodCall(mc) => {
            let method = mc.method.to_string();
            if method == "unwrap" || method == "expect" {
                return channel_target(&mc.receiver);
            }
            if method == "lock" {
                if let Expr::Path(p) = &*mc.receiver {
                    if let Some(seg) = p.path.segments.last() {
                        let base = seg.ident.to_string();
                        return (base.clone(), Some(base));
                    }
                }
                return ("channel".to_string(), None);
            }
            ("channel".to_string(), None)
        }
        Expr::Path(p) => p
            .path
            .segments
            .last()
            .map(|s| (s.ident.to_string(), None))
            .unwrap_or_else(|| ("channel".to_string(), None)),
        _ => ("channel".to_string(), None),
    }
}

struct ChannelCollector {
    starts: Vec<usize>,
    stmt_stack: Vec<usize>,
    edits: Vec<Edit>,
    wrappers: std::collections::HashSet<String>,
    resources: Vec<Resource>,
}

impl<'ast> Visit<'ast> for ChannelCollector {
    fn visit_stmt(&mut self, node: &'ast Stmt) {
        let start = lc_offset(&self.starts, node.span().start());
        self.stmt_stack.push(start);
        syn::visit::visit_stmt(self, node);
        self.stmt_stack.pop();
    }

    fn visit_expr_method_call(&mut self, node: &'ast ExprMethodCall) {
        if let Some(op) = channel_op(&node.method.to_string()) {
            let (resource, wrapper) = channel_target(&node.receiver);
            if let Some(w) = wrapper {
                self.wrappers.insert(w);
                self.resources.push(Resource {
                    name: resource.clone(),
                    kind: "ChannelWrapper".to_string(),
                    display: Some(resource.clone()),
                    ..Default::default()
                });
            }
            if let Some(pos) = self.stmt_stack.last().copied() {
                self.edits.push(Edit {
                    start: pos,
                    end: pos,
                    text: format!("cir_trace::record(\"{op}\", \"{resource}\"); "),
                });
                self.resources.push(Resource {
                    name: resource.clone(),
                    kind: "Channel".to_string(),
                    display: Some(resource),
                    ..Default::default()
                });
            }
        }
        syn::visit::visit_expr_method_call(self, node);
    }
}

struct Namer {
    starts: Vec<usize>,
    edits: Vec<Edit>,
    resources: Vec<Resource>,
    skip_semaphore: bool,
    wrappers: std::collections::HashSet<String>,
}

impl Namer {
    fn name_constructors(&mut self, local: &syn::Local) {
        let Some(init) = &local.init else { return };
        let mut collector = CtorCollector {
            starts: self.starts.clone(),
            hits: Vec::new(),
            skip_semaphore: self.skip_semaphore,
            closure_depth: 0,
            current_field: None,
        };
        collector.visit_expr(&init.expr);
        if collector.hits.is_empty() {
            return;
        }
        let base = match &local.pat {
            Pat::Ident(i) => i.ident.to_string(),
            _ => "res".to_string(),
        };
        let mut counters: BTreeMap<&'static str, usize> = BTreeMap::new();
        for hit in collector.hits {
            let k = counters.entry(hit.kind).or_insert(0);
            let display = match &hit.field {
                Some(field) => field.clone(),
                None => format!("{}_{}{}", base, hit.kind.to_lowercase(), *k),
            };
            let name = format!("{display}#{}", hit.new_start);
            *k += 1;
            let is_wrapper = self.wrappers.iter().any(|w| {
                w == &base || w.starts_with(&base) || base.starts_with(w.as_str())
            });
            let kind = if hit.kind == "Mutex" && is_wrapper {
                "ChannelWrapper"
            } else {
                hit.kind
            };
            let text = if hit.empty_args {
                format!("\"{name}\"")
            } else {
                format!("\"{name}\", ")
            };
            self.edits.push(Edit {
                start: hit.new_start,
                end: hit.new_end,
                text: "new_named".to_string(),
            });
            self.edits.push(Edit { start: hit.open_brace, end: hit.open_brace, text });
            self.resources.push(Resource {
                name,
                kind: kind.to_string(),
                display: Some(display),
                site: Some(hit.new_start.to_string()),
                ..Default::default()
            });
        }
    }
}

impl<'ast> Visit<'ast> for Namer {
    fn visit_item_static(&mut self, node: &'ast syn::ItemStatic) {
        let mut collector = CtorCollector {
            starts: self.starts.clone(),
            hits: Vec::new(),
            skip_semaphore: self.skip_semaphore,
            closure_depth: 0,
            current_field: None,
        };
        collector.visit_expr(&node.expr);
        let base = node.ident.to_string();
        for hit in collector.hits {
            let name = format!("{}_{}0", base, hit.kind.to_lowercase());
            let text = if hit.empty_args {
                format!("\"{name}\"")
            } else {
                format!("\"{name}\", ")
            };
            self.edits.push(Edit { start: hit.new_start, end: hit.new_end, text: "new_named".into() });
            self.edits.push(Edit { start: hit.open_brace, end: hit.open_brace, text });
            self.resources.push(Resource {
                name,
                kind: hit.kind.to_string(),
                site: Some(hit.new_start.to_string()),
                ..Default::default()
            });
        }
        syn::visit::visit_item_static(self, node);
    }

    fn visit_stmt(&mut self, node: &'ast Stmt) {
        if let Stmt::Local(local) = node {
            self.name_constructors(local);
        }
        syn::visit::visit_stmt(self, node);
    }
}

struct MainFinder {
    starts: Vec<usize>,
    open: Option<usize>,
    close: Option<usize>,
}

impl<'ast> Visit<'ast> for MainFinder {
    fn visit_item_fn(&mut self, node: &'ast syn::ItemFn) {
        if node.sig.ident == "main" {
            let open = lc_offset(&self.starts, node.block.brace_token.span.open().start());
            let close = lc_offset(&self.starts, node.block.brace_token.span.close().start());
            self.open = Some(open + 1);
            self.close = Some(close);
        }
        syn::visit::visit_item_fn(self, node);
    }
}

/// Remove `Mutex`/`Condvar` from `use std::sync::{...}` and simple uses so the
/// names can be provided by `cir_trace::sync`.
fn brace_depth_at(src: &str, index: usize) -> usize {
    let mut depth = 0usize;
    let mut in_str = false;
    let mut esc = false;
    for (i, c) in src.char_indices() {
        if i >= index {
            break;
        }
        if in_str {
            if esc {
                esc = false;
            } else if c == '\\' {
                esc = true;
            } else if c == '"' {
                in_str = false;
            }
            continue;
        }
        match c {
            '"' => in_str = true,
            '{' => depth += 1,
            '}' => depth = depth.saturating_sub(1),
            _ => {}
        }
    }
    depth
}

/// A crate-root `use cir_trace::sync::{Mutex, Condvar}` does not reach items
/// inside `mod`. Re-import the wrappers in the module that originally imported
/// `std::sync::{Mutex, Condvar}`.
fn scoped_sync_use(src_before: &str, names: &[&str]) -> String {
    if names.is_empty() || brace_depth_at(src_before, src_before.len()) == 0 {
        return String::new();
    }
    format!("use crate::cir_trace::sync::{{{}}};", names.join(", "))
}

/// Prune std sync names from the use tree, retaining its grouping so legacy
/// simple imports have the same spelling. Reintroduce wrappers in that scope.
fn sync_use_tree(tree: &syn::UseTree, prefix: &str, wrapped: &mut Vec<String>) -> Option<String> {
    match tree {
        syn::UseTree::Path(p) => {
            let next = format!("{prefix}{}::", p.ident);
            sync_use_tree(&p.tree, &next, wrapped).map(|tail| format!("{}::{tail}", p.ident))
        }
        syn::UseTree::Group(g) => {
            let kept: Vec<_> = g.items.iter().filter_map(|t| sync_use_tree(t, prefix, wrapped)).collect();
            (!kept.is_empty()).then(|| format!("{{{}}}", kept.join(", ")))
        }
        syn::UseTree::Name(n) => {
            if prefix == "std::sync::" && matches!(n.ident.to_string().as_str(), "Mutex" | "Condvar") {
                wrapped.push(n.ident.to_string());
                None
            } else { Some(n.ident.to_string()) }
        }
        syn::UseTree::Rename(n) => {
            let text = format!("{} as {}", n.ident, n.rename);
            if prefix == "std::sync::" && matches!(n.ident.to_string().as_str(), "Mutex" | "Condvar") {
                wrapped.push(text);
                None
            } else { Some(text) }
        }
        syn::UseTree::Glob(_) => Some("*".into()),
    }
}

fn rewrite_imports(src: &str) -> String {
    struct Imports<'a> {
        src: &'a str,
        starts: Vec<usize>,
        edits: Vec<Edit>,
    }
    impl<'ast> Visit<'ast> for Imports<'_> {
        fn visit_item_use(&mut self, node: &'ast syn::ItemUse) {
            let mut wrapped = Vec::new();
            let kept = sync_use_tree(&node.tree, "", &mut wrapped);
            if wrapped.is_empty() { return; }
            let start = lc_offset(&self.starts, node.span().start());
            let end = lc_offset(&self.starts, node.span().end());
            let mut text = kept.map(|tree| format!("use {tree};")).unwrap_or_default();
            let local = scoped_sync_use(&self.src[..start], &wrapped.iter().map(String::as_str).collect::<Vec<_>>());
            text.push_str(&local);
            // Root unaliased imports are already supplied by the header.
            // Aliases need their own imports even at crate root.
            if local.is_empty() {
                let aliases: Vec<_> = wrapped.iter().filter(|name| name.contains(" as ")).collect();
                if !aliases.is_empty() {
                    text.push_str(&format!("use crate::cir_trace::sync::{{{}}};",
                        aliases.iter().map(|s| s.as_str()).collect::<Vec<_>>().join(", ")));
                }
            }
            self.edits.push(Edit { start, end, text });
        }
    }
    let mut result = src.to_string();
    if let Ok(file) = syn::parse_file(src) {
        let mut imports = Imports { src, starts: line_starts(src), edits: Vec::new() };
        imports.visit_file(&file);
        imports.edits.sort_by_key(|edit| std::cmp::Reverse(edit.start));
        for edit in imports.edits { result.replace_range(edit.start..edit.end, &edit.text); }
    }
    result
        .replace("std::sync::Mutex", "cir_trace::sync::Mutex")
        .replace("std::sync::Condvar", "cir_trace::sync::Condvar")
}

fn limitations_of(src: &str) -> Vec<String> {
    let mut out = Vec::new();
    for (token, note) in [
        ("RwLock", "RwLock is not instrumented"),
        ("Barrier", "Barrier is not instrumented"),
        ("Once", "Once is not instrumented"),
        ("atomic", "atomics are not instrumented (no value events)"),
        ("thread::scope", "thread::scope could not be fully instrumented"),
        ("async ", "async/await is not supported"),
        ("select!", "select is not supported"),
    ] {
        if src.contains(token) {
            out.push(note.to_string());
        }
    }
    out
}


fn matching_brace(s: &str) -> Option<usize> {
    let bytes = s.as_bytes();
    let mut depth = 0i32;
    let mut i = 0usize;
    let mut in_str = false;
    let mut esc = false;
    while i < bytes.len() {
        let c = bytes[i] as char;
        if in_str {
            if esc { esc = false; }
            else if c == '\\' { esc = true; }
            else if c == '"' { in_str = false; }
            i += 1;
            continue;
        }
        match c {
            '"' => in_str = true,
            '{' => depth += 1,
            '}' => {
                if depth == 0 { return Some(i); }
                depth -= 1;
            }
            _ => {}
        }
        i += 1;
    }
    None
}

/// Remove any `mod concir_sync;` / `mod concir_sync { .. }` the model wrote:
/// the harness links `concir_sync` as an external crate.
fn strip_concir_sync_mod(src: &str) -> (String, Vec<String>) {
    let mut notes = Vec::new();
    let mut out = String::new();
    let mut rest = src;
    const NEEDLE: &str = "mod concir_sync";
    while let Some(i) = rest.find(NEEDLE) {
        out.push_str(&rest[..i]);
        let after = &rest[i + NEEDLE.len()..];
        let lead = after.len() - after.trim_start().len();
        if after.trim_start().starts_with('{') {
            let block = &after[lead + 1..];
            if let Some(end) = matching_brace(block) {
                notes.push("stripped inline `mod concir_sync {..}`".to_string());
                rest = &block[end + 1..];
                continue;
            }
        } else if after.trim_start().starts_with(';') {
            notes.push("stripped `mod concir_sync;`".to_string());
            rest = &after[lead + 1..];
            continue;
        }
        out.push_str(NEEDLE);
        rest = &rest[i + NEEDLE.len()..];
    }
    out.push_str(rest);
    (out, notes)
}

pub fn wrap(src: &str) -> Result<Wrapped, String> {
    let (clean, harness_notes) = strip_concir_sync_mod(src);
    let src: &str = &clean;
    let file: File = syn::parse_file(src).map_err(|e| format!("parse error: {e}"))?;
    let starts = line_starts(src);

    let skip_semaphore = src.contains("struct Semaphore") || src.contains("impl Semaphore");
    let mut channels = ChannelCollector {
        starts: starts.clone(), stmt_stack: Vec::new(), edits: Vec::new(),
        wrappers: Default::default(), resources: Vec::new(),
    };
    channels.visit_file(&file);
    let mut namer = Namer { starts: starts.clone(), edits: Vec::new(),
                            resources: Vec::new(), skip_semaphore,
                            wrappers: channels.wrappers.clone() };
    namer.visit_file(&file);
    let mut spawns = SpawnCollector::new(starts.clone());
    spawns.visit_file(&file);
    spawns.emit(&mut namer.edits, &mut namer.resources);
    namer.edits.extend(channels.edits);
    namer.resources.extend(channels.resources);
    {
        // Distinct construction sites are distinct instances even when they
        // share a name (e.g. two `S { m: Mutex::new(..) }` values).
        let mut seen = std::collections::HashSet::new();
        namer.resources.retain(|r| {
            seen.insert((r.name.clone(), r.kind.clone(), r.site.clone()))
        });
    }

    let mut finder = MainFinder { starts: starts.clone(), open: None, close: None };
    finder.visit_file(&file);
    let (Some(main_open), Some(main_close)) = (finder.open, finder.close) else {
        return Err("no `fn main` found".to_string());
    };

    // Insert init() at the top of main and finish() before its closing brace.
    let mut edits = namer.edits;
    edits.push(Edit {
        start: main_open,
        end: main_open,
        text: " cir_trace::init();".to_string(),
    });
    edits.push(Edit {
        start: main_close,
        end: main_close,
        text: " cir_trace::finish();".to_string(),
    });

    // Header: module declaration + imports.
    let uses_sync = src.contains("Mutex") || src.contains("Condvar");
    let mut header = String::new();
    if !src.contains("mod cir_trace") {
        header.push_str("mod cir_trace;\n");
    }
    if uses_sync && !src.contains("use cir_trace::sync") && !src.contains("use crate::cir_trace::sync") {
        header.push_str("use cir_trace::sync::{Mutex, Condvar};\n");
    }
    edits.push(Edit { start: leading_header_len(src), end: leading_header_len(src), text: header });

    let mut annotated = src.to_string();
    edits.sort_by(|a, b| b.start.cmp(&a.start).then(b.end.cmp(&a.end)));
    for edit in edits {
        annotated.replace_range(edit.start..edit.end, &edit.text);
    }
    // Then rewrite imports on the annotated text (offset-independent).
    annotated = rewrite_imports(&annotated);

    let mut limitations = limitations_of(&annotated);
    limitations.extend(spawns.limitations);
    Ok(Wrapped {
        annotated,
        runtime: RUNTIME.to_string(),
        resources: namer.resources,
        limitations,
        harness_notes,
    })
}
